githubConfigUrl: "https://github.com/skynet-bd"
githubConfigSecret: "gha-runner-scale-set-secrets"
maxRunners: 10
minRunners: 0
# with containerMode.type=kubernetes, we will populate the template.spec with following pod spec
template:
  spec:
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      resources:
        limits:
          cpu: 200m
          memory: 1024Mi
        requests:
          cpu: 50m
          memory: 256Mi
      env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
controllerServiceAccount:
  namespace: github-runner
  # name: gha-runner-scale-set-controller
  name: ghrc-gha-rs-controller
